{
	"weibo": "微博",
	"alipay": "支付宝",
	"stripe": "Stripe",
	"accountBalance": "账户余额",
	"wechat": "微信",
	"stepTime": {
		"oneMonth": "一个月",
		"threeMonth": "三个月",
		"sixMonth": "六个月",
		"twelveMonth": "十二个月"
	},
	"route": {
		"login": "登录",
		"register": "注册",
		"resetPasswords": "忘记密码",
		"home": "首页",
		"search": "红人",
		"searchBloggers": "红人",
		"bloggerDetail": "kol详情",
		"notfound": "404页面",
		"analytics": "舆情分析",
		"analyticsLanding": "舆情分析",
		"analyticsDetail": "舆情详情",
		"activities": "活动",
		"myActivities": "我的活动",
		"activitiesDetail": "活动详情",
		"my": "个人主页",
		"myIndex": "我的主页面",
		"create": "创建活动",
		"createActivies": "创建活动"
	},
	"search": {
		"search": "搜索",
		"searchPlaceholder": "请输入KOL名字或关键词搜索"
	},
	"common": {
		"class": "class-zh",
		"edit": "编辑",
		"cancel": "取消",
		"save": "保存",
		"logOut": "退出登录",
		"lang": {
			"zh": "中文",
			"en": "English",
			"SwitchLanguageSuccess": "切换语言成功"
		},
		"porductDes": "产品介绍",
		"serviceTerms": "服务条款",
		"aboutUs": "关于我们",
		"contactOur": "联系我们",
		"address": "地址",
		"home": "首页",
		"information": "资讯",
		"kollibrary": "红人库",
		"myactives": "我的活动",
		"logout": "退出",
		"acountinformation": "账号信息",
		"systemset": "系统设置",
		"myWallet": "我的钱包",
		"notfoundTitle": "网站管理员说您无法进入此页面...",
		"notfoundDesc": "请检查您输入的URL是否正确，或单击下面的按钮返回主页",
		"goHome": "回到首页",
		"notfoundReserved": "保留所有权利",
		"notfoundReservedLink": "图迪科技",
		"oops": "哎呀!",
		"fansNumber": "粉丝数",
		"postNumber": "帖子数",
		"commentNumber": "评论数",
		"personInformation": "个人资料",
		"plateform": "平台",
		"signature": "签名",
		"similarKol": "类似红人",
		"postHot": "热门帖子",
		"postStatistics": "历史帖子统计",
		"operationalHeat": "运营热度",
		"worldCloud": "品牌提及词云",
		"seeMore": "查看更多"
	},
	"home": {
		"title": "系统登录"
	},
	"my": {
		"accountMsg": "账户信息",
		"wallet": "我的钱包",
		"system": "系统设置",
		"walletMng": "钱包管理",
		"accountRecharge": "账户充值",
		"accountInformation": "账户资料",
		"name": "联系人",
		"email": "注册邮箱",
		"mobile": "联系电话",
		"brandName": "公司名字",
		"brandType": "公司类型",
		"brandCountry": "公司国家",
		"brandWebsite": "企业官方网站",
		"barndAttention": "关注行业",
		"transactionHour": "交易时间",
		"transactionType": "交易类型",
		"transactionAounmt": "交易金额",
		"transactionBalance": "余额",
		"operating": "操作",
		"invoice": "开发票",
		"transactionDetail": "交易详情",
		"recharge": "去充值",
		"eventHosting": "托管中的活动费用（共3个活动）",
		"availableBalance": "可用余额",
		"startTime": "开始时间",
		"endTime": "结束时间",
		"to": "至",
		"selectAll": "select-all-zh",
		"next": "下一步",
		"invoiceTotalInfo": "笔交易，共",
		"invoiceTitle": "开具发票",
		"invoiceForm": {
			"headType": "抬头类型",
			"headnumber": "发票抬头",
			"taxnumber": "税号",
			"address": "地址和电话",
			"bank": "开户行和账号",
			"email": "电子发票接收邮箱"
		},
		"submit": "提交",
		"invoiceNumber": "发票数量",
		"invoiceCause": "发票事由",
		"invoiceCauseInfo": "平台服务费",
		"billingParty": "开票方",
		"invoiceTotal": "发票总额",
		"zhang": "张",
		"receiveInfo": "我们已将电子发票发送至你的邮箱",
		"attentionCheck": "请注意查收。",
		"goWallet": "返回钱包",
		"changePwd": "修改密码",
		"inputNowpuc": "请输入当前密码",
		"inputNewPwd": "请输入新密码（6-20位数字或字母）",
		"inputNewPwdAging": "请再次输入新密码",
		"save": "保存",
		"updatePwdSuc": "密码重置成功",
		"updatePwdInfo": "请妥善保管您的账户信息",
		"costsStart": "Activity costs in hosting (",
		"costsEnd": "event total)",
		"payType": "支付方式",
		"banlace": "账户余额",
		"rechargeAmount": "充值金额",
		"alipay": "支付宝",
		"stripe": "Stripe",
		"payForAlipay": "支付宝支付",
		"Paying": "正在支付",
		"abandonPayInfo": "还有支付正在进行, 是否继续?"
	},
	"login": {
		"title": "登录到Navigate",
		"loginForm": {
			"email": "请输入邮箱",
			"password": "请输入密码",
			"infoPwd": "忘记密码?",
			"login": "登录",
			"infoJoin": "还没有加入Navigate？",
			"goRegister": "去注册"
		},
		"msgEmail": "请输入有效邮箱",
		"msgPassword": "密码为6至20位数字或字母，区分大小写",
		"geeTest": "点击按钮进行验证"
	},
	"register": {
		"title": "免费注册",
		"registerForm": {
			"type": "请选择品牌或企业",
			"brandName": "品牌或者企业名",
			"name": "联系人名字",
			"email": "请输入邮箱",
			"password": "请输入密码（6-20位数字或字母）",
			"infoAgree": "注册即代表同意Navigate的",
			"service": "服务条款",
			"register": "立马注册",
			"registered": "已注册",
			"goLogin": "去登录"
		},
		"msgBrandName": "品牌或者企业名称不能为空",
		"msgRealName": "请输入真实名字",
		"msgEmail": "请输入有效邮箱",
		"msgPassword": "密码为6至20位数字或字母，区分大小写",
		"msgCheck": "请勾选服务条款",
		"infoSuc": "注册成功",
		"infoSucTip": "感谢注册Navigate，我们已将验证邮件发送至你的邮箱",
		"infoSucTip2": "请在二十四小时内激活你的Navigate账号",
		"goHome": "返回登陆首页",
		"geeTest": "点击按钮进行验证"
	},
	"resetPassword": {
		"title": "忘记密码",
		"resetPwdForm": {
			"email": "请输入邮箱",
			"password": "请输入新密码"
		},
		"sendCode": "获取验证码",
		"infoTime": "后可重新获取",
		"infoSend": "您的6位数验证码已发送至",
		"infoCheck": "请前往查收",
		"save": "保存修改",
		"goHome": "返回登录首页",
		"forgetPwd": "忘记密码",
		"infoSuc": "新密码保存成功",
		"infoSave": "请妥善保管您的账户信息",
		"msgEmail": "请输入有效邮箱",
		"msgPassword": "密码为6至20位数字或字母，区分大小写",
		"msgEmailNoregister": "邮箱没有注册",
		"msgPwdError": "新密码格式错误",
		"reagin": "重新获取",
		"msgVerfid": "请输入正确的验证码"
	},
	"verification": {
		"verificationSucss": "认证成功",
		"pleaseGoToLogin": "请到登陆页登陆",
		"verificationError": "认证失败",
		"pleaseTryAgain": "请再试一遍"
	},
	"koltype": {
		"fav": "收藏的 KOL",
		"worked": "合作的 KOL"
	},
	"activeProcess": {
		"all": "全部",
		"draft": "草稿",
		"pending": "待开始",
		"inProgress": "已开始",
		"finished": "已完成",
		"rejected": "已失效"
	},
	"campaignStep": {
		"stepOne": "选择活动类型",
		"stepTwo": "填写活动需求",
		"stepThree": "上传活动物料",
		"stepFour": "确认活动策略",
		"stepFive": "预存活动费用"
	},
	"campaignTabs": {
		"name": "活动名称",
		"startAt": "活动开始时间",
		"updateAt": "活动更新时间",
		"expenditure": "活动支出",
		"totalPlateformValue": "总2dmVlaue",
		"status": "状态"
	},
	"produced": "来自navigation的推广",
	"plateformValue": "Navigate平台评估推文产生的影响力指标，根据帖子产生的观看量、点赞量、评论量、转发量等数据计算而来。",
	"plateformScore": "Navigate平台根据KOL的影响力、推文媒体价值、活跃度、发文频率、互动情况、品牌合作度等因素综合计算而来，为0～1000的数值。",
	"plateformPrice": "指和KOL合作投放内容至某一平台的合作底薪，和KOL个人影响力、平台评分（2dmScore）、历史品牌合作表现有关。",
	"operationalHeat": "表示KOL在不同时间发布的推文数量及推文产生的影响力，发布推文越多气泡纵坐标越高，推文影响力越大气泡越大。",
	"cooperationConfirmation": "KOL合作确认",
	"tweetPost": "推文发布",
	"activityCosts": "活动费用",
	"actualPlatformValue": "2dmValue",
	"cooperationConfirmationTip": "代表所有KOL确认同意或拒绝本次活动合作的进度（已确认KOL人数/所有指定合作的KOL人数）",
	"tweetPostTip": "代表本活动所有推文的发布进度 （已发布推文数/所有需要发布的推文数）",
	"activityCostsTip": "代表活动实际消耗费用进度，需注意当KOL同意合作后已经产生合作底薪费用（实际消耗费用/最高预算）",
	"actualPlatformValueTip": "代表活动实际带来的媒体价值与预测本活动最有可能达到的媒体价值，需注意实际媒体价值可能超出预测价值（实际产生媒体价值/预测最有可能产生的媒体价值）",
	"information": {
		"name": "联系人",
		"displayName": "昵称",
		"email": "联系邮箱",
		"phone": "联系电话",
		"currency": "交易币种",
		"companyName": "公司名字",
		"companyType": "公司类型",
		"companyCountry": "公司国家",
		"website": "公司网站",
		"industry": "关注行业",
		"pleasePhone": "请输入手机号",
		"pleaseEmail": "联系人邮箱",
		"pleaseName": "请输入联系人姓名",
		"notNull": "不能为空",
		"laterVer": "后再验证",
		"getVer": "获取验证码",
		"pleaseVer": "请输入验证码",
		"choseM": "选择币种",
		"tip": "Tips: 请仔细确认平台交易币种，一旦选定无法变更",
		"sex": "性别",
		"country": "国家",
		"pleaseChose": "请选择",
		"morThree": "最多三个",
		"save": "保存",
		"brand": "品牌端",
		"agency": "广告方",
		"cny": "人民币",
		"usd": "美元",
		"aud": "澳元",
		"wellcomText": "欢迎加入Navigate！为了给您提供更好的服务，请在使用前填写以下信息：",
		"china": "中国",
		"au": "澳大利亚",
		"usa": "美国",
		"otherPhone": "自定义国际区号",
		"pleasFillPhone": "填写手机号时请添加归属国际区号,否则无法接收验证码"
	},
	"campaign": {
		"form": {
			"campaignName": "活动名称",
			"industries": "推广行业",
			"brandName": "品牌名字",
			"brandDescription": "品牌介绍",
			"brandUrl": "品牌介绍链接",
			"targetAreas": "目标区域",
			"budget": "活动预算",
			"startDate": "活动开始时间",
			"continuous": "活动持续周期",
			"duration": "一周",
			"copy": "活动文案",
			"refLink": "活动跳转链接",
			"upLoadImg": "上传图片"
		},
		"tabs": {
			"banner": "植入",
			"custom": "定制"
		},
		"bannerStep": [
			"选择活动类型",
			"填写活动需求",
			"上传活动内容",
			"确认活动策略",
			"预存活动费用"
		],
		"customStep": [
			"选择活动类型",
			"填写活动需求",
			"上传活动内容",
			"确认活动策略",
			"预存活动费用"
		]
	},
	"btn": {
		"cancel": "取消",
		"next": "下一步",
		"previous": "上一步",
		"saveAndNext": "保存并下一步",
		"previewCampaign": "活动预览",
		"contentPreview": "植入内容预览",
		"customCampaignStrategy": "自定义活动策略",
		"save": "保存",
		"refresh": "换一波",
		"confirm": "确认",
		"restoreMatch": "放弃自定义，重置系统策略",
		"add": "添加",
		"added": "已添加",
		"pay": "去支付",
		"back": "返回",
		"walletPayment": "余额支付"
	}
}
