export default {
	'weibo': 'weibo',
	'alipay': 'Alipay',
	'accountBalance': 'account balance',
	'wechat': 'Wechat',
	'activity': 'vitality',
	'stepTime': {
	  'oneMonth': 'A month',
	  'threeMonth': 'trimester ',
	  'sixMonth': 'Six months',
	  'twelveMonth': 'twelvemonth'
	},
	'route': {
	  'login': 'entry',
	  'register': 'registe',
	  'resetPasswords': 'Forget the password',
	  'home': 'home page ',
	  'search': 'a favourite with sb. in powe',
	  'searchBloggers': 'a favourite with sb. in powe',
	  'bloggerDetail': 'Kol details',
	  'notfound': '404 page',
	  'analytics': 'public opinion analysis',
	  'analyticsLanding': 'public opinion analysis',
	  'analyticsDetail': 'public opinion details',
	  'activities': 'activity',
	  'myActivities': 'My Activities',
	  'activitiesDetail': 'Activity Details',
	  'my': 'personal homepage ',
	  'myIndex': 'My main page.',
	  'create': 'Create an activity',
	  'createActivies': 'Create an activity'
	},
	'search': {
	  'search': 'search',
	  'searchPlaceholder': 'Please enter a KOL name or keyword search'
	},
	'common': {
	  'class': 'class-zh',
	  'edit': 'edit',
	  'cancel': 'cancel',
	  'save': 'save',
	  'logOut': 'log off',
	  'lang': {
		'zh': 'the Chinese language',
		'SwitchLanguageSuccess': 'Successful switching language'
	  },
	  'porductDes': 'product presentation',
	  'serviceTerms': 'term of service ',
	  'aboutUs': 'About Us',
	  'contactOur': 'contact us',
	  'address': 'address',
	  'home': 'home page ',
	  'information': 'information ',
	  'kollibrary': "Red People's Library",
	  'myactives': 'My Activities',
	  'logout': 'withdraw from',
	  'acountinformation': 'Account No. information',
	  'systemset': 'System setting',
	  'myWallet': 'My wallet',
	  'notfoundTitle': 'The webmaster said you could not access this page.',
	  'notfoundDesc': 'Please check that the URL you entered is correct, or click the button below to return to the home page',
	  'goHome': 'Back to the home page.',
	  'notfoundReserved': 'All rights reserved',
	  'notfoundReservedLink': "Tudy's technology",
	  'oops': 'Oh!',
	  'fansNumber': 'Number of fans',
	  'postNumber': 'Number of posts',
	  'commentNumber': 'Number of comments',
	  'personInformation': 'personal profile',
	  'plateform': 'terrace',
	  'signature': "sign one's name",
	  'similarKol': 'a similar red man',
	  'postHot': 'Top Posts',
	  'postStatistics': 'Historical post statistics',
	  'operationalHeat': 'Operation heat',
	  'worldCloud': 'Brand refers to the word cloud',
	  'seeMore': 'View more'
	},
	'home': {
	  'title': 'System login'
	},
	'my': {
	  'accountMsg': 'Account information',
	  'wallet': 'My wallet',
	  'system': 'System setting',
	  'walletMng': 'wallet management',
	  'accountRecharge': 'Account recharge',
	  'accountInformation': 'Account information',
	  'name': 'contacts',
	  'email': 'Registered mailbox',
	  'mobile': 'contact numbe',
	  'brandName': 'Company name',
	  'brandType': 'Type of company',
	  'brandCountry': 'Company Country',
	  'brandWebsite': 'Official website of the enterprise',
	  'barndAttention': 'Focus on the industry',
	  'transactionHour': ' exchange hour ',
	  'transactionType': 'Transaction type',
	  'transactionAounmt': 'Transaction Amount',
	  'transactionBalance': 'balance',
	  'operating': 'operate',
	  'invoice': 'draw a bill',
	  'transactionDetail': 'trading particulars',
	  'recharge': 'to recharge',
	  'eventHosting': 'Activities in custody (3 activities in total)',
	  'availableBalance': ' available balance ',
	  'startTime': 'start time',
	  'endTime': 'terminal time ',
	  'to': 'to',
	  'selectAll': 'select-all-zh',
	  'next': 'next step',
	  'invoiceTotalInfo': 'A deal, a total of',
	  'invoiceTitle': 'Issue an invoice',
	  'invoiceForm': {
		'headType': 'Head type',
		'headnumber': 'invoice title',
		'taxnumber': 'duty paragraph ',
		'address': 'Address and Phone',
		'bank': 'Opening bank and account numbe',
		'email': 'E-Invoice Receiving E-mail'
	  },
	  'submit': 'submit (a problem, etc.) to',
	  'invoiceNumber': 'Number of invoices',
	  'invoiceCause': 'subject matter of the invoice',
	  'invoiceCauseInfo': 'platform service charge',
	  'billingParty': 'Invoicing Party',
	  'invoiceTotal': 'Total invoice amount',
	  'zhang': 'fix ',
	  'receiveInfo': 'We have sent the electronic invoice to your mailbox',
	  'attentionCheck': 'Please pay attention to the collection.',
	  'goWallet': 'Return to the wallet',
	  'changePwd': 'Modify the password',
	  'inputNowpuc': 'Please enter the current password',
	  'inputNewPwd': 'Please enter a new password (6 / 20 digits or letters)',
	  'inputNewPwdAging': 'Please enter a new password again',
	  'save': 'save',
	  'updatePwdSuc': 'Password reset succeeded',
	  'updatePwdInfo': 'Please keep your account information properly',
	  'costsStart': 'Activity costs in hosting (',
	  'costsEnd': 'event total)',
	  'payType': ' mode of payment ',
	  'banlace': 'account balance',
	  'rechargeAmount': 'Recharge Amount',
	  'alipay': 'Alipay',
	  'payForAlipay': 'Alipay payment',
	  'Paying': 'being paid',
	  'abandonPayInfo': 'and the payment is ongoing, whether continue?'
	},
	'login': {
	  'title': 'Log in to Navigate',
	  'loginForm': {
		'email': 'Please enter a mailbox',
		'password': 'Enter Your PIN',
		'infoPwd': 'Forget the password?',
		'login': 'entry',
		'infoJoin': "I haven't joined Navigate? yet.",
		'goRegister': 'to registe'
	  },
	  'msgEmail': 'Please enter a valid mailbox',
	  'msgPassword': 'Passwords are 6 to 20 digits or letters, case - sensitive.',
	  'geeTest': 'Click the button to verify'
	},
	'register': {
	  'title': 'Free registration',
	  'registerForm': {
		'type': 'Please select a brand or enterprise',
		'brandName': 'Brand or enterprise name',
		'name': 'Contact name',
		'email': 'Please enter a mailbox',
		'password': 'Please enter a password (6-20 digits or letters)',
		'infoAgree': 'The registration is the consent of the Representative.',
		'service': 'term of service ',
		'register': 'Register now',
		'registered': 'Registered',
		'goLogin': 'to log in'
	  },
	  'msgBrandName': 'Brand or enterprise name cannot be empty',
	  'msgRealName': 'Please enter a real name',
	  'msgEmail': 'Please enter a valid mailbox',
	  'msgPassword': 'Passwords are 6 to 20 digits or letters, case - sensitive.',
	  'msgCheck': 'Please check the service terms',
	  'infoSuc': 'Registration is successful',
	  'infoSucTip': 'Thanks for registering Navigate, we have sent the verification mail to your mailbox.',
	  'infoSucTip2': 'Please activate your Tate account within twenty-four hours',
	  'goHome': 'Return to the home page',
	  'geeTest': 'Click the button to verify'
	},
	'resetPassword': {
	  'title': 'Forget the password',
	  'resetPwdForm': {
		'email': 'Please enter a mailbox',
		'password': 'Please enter a new password'
	  },
	  'sendCode': 'Get a verification code',
	  'infoTime': 'It can be reacquired after it is available.',
	  'infoSend': 'Your 6-digit verification code has been sent to',
	  'infoCheck': 'Please go to the check-and-go',
	  'save': 'Save changes',
	  'goHome': 'Return to login home page',
	  'forgetPwd': 'Forget the password',
	  'infoSuc': 'New password saved successfully',
	  'infoSave': 'Please keep your account information properly',
	  'msgEmail': 'Please enter a valid mailbox',
	  'msgPassword': 'Passwords are 6 to 20 digits or letters, case - sensitive.',
	  'msgEmailNoregister': 'The mailbox is not registered',
	  'msgPwdError': 'New password format erro',
	  'reagin': 'reacquire',
	  'msgVerfid': 'Please enter the correct verification code'
	},
	'verification': {
	  'verificationSucss': 'Certification success',
	  'pleaseGoToLogin': 'Please log in on the login page.',
	  'verificationError': 'Authentication failed',
	  'pleaseTryAgain': 'Please try again'
	},
	'koltype': {
	  'fav': 'Collection of KOL',
	  'worked': 'Cooperative KOL'
	},
	'activeProcess': {
	  'all': 'whole',
	  'draft': 'rough draft',
	  'pending': 'Wait to start.',
	  'inProgress': 'Started',
	  'finished': 'off the stocks ',
	  'rejected': 'Ineffective'
	},
	'campaignStep': {
	  'stepOne': 'Select the type of activity',
	  'stepTwo': 'Fill in the activity requirements',
	  'stepThree': 'Upload active material',
	  'stepFour': 'Confirm the activity policy',
	  'stepFive': 'Pre-stored activity expenses'
	},
	'campaignTabs': {
	  'name': 'Activity name',
	  'startAt': 'activity start time',
	  'updateAt': 'Activity update time',
	  'expenditure': 'activity expenditure',
	  'totalPlateformValue': 'Total 2dmVlaue',
	  'status': 'status'
	},
	'produced': 'Promotion from navigation',
	'plateformValue': 'The Navigate platform evaluates the influence index of tweets, and calculates them according to the data such as the amount of observation, the amount of comments, the amount of comments and the amount of transfer generated by posts.',
	'plateformScore': "Navigate platform is calculated comprehensively according to KOL's influence, promotion media value, activity, distribution frequency, interaction, brand cooperation degree and other factors, which is 0~1000. ",
	'plateformPrice': 'It refers to the cooperation base salary of the delivery of the content to a certain platform in cooperation with KOL, and the influence of KOL personal influence, platform score (2 dmScore) and historical brand cooperation.',
	'operationalHeat': 'The number of tweets issued by KOL at different times and the influence of the tweet are indicated. The higher the number of air bubbles is released, the greater the influence of the push force and the greater the bubble.',
	'cooperationConfirmation': 'KOL cooperation confirmation',
	'tweetPost': 'tweet release',
	'activityCosts': 'Activity expense',
	'actualPlatformValue': '2dmValue',
	'cooperationConfirmationTip': 'Progress made on behalf of all KOL to confirm or reject the cooperation of the event (the number of KOL/ all the number of KOL designated for cooperation has been confirmed)',
	'tweetPostTip': 'Represents the progress of all tweets for this event (number of tweets posted / number of tweets required).',
	'activityCostsTip': "Progress on the actual consumption of the representative's activities, and it is to be noted that when the KOL agrees to cooperate, the cost of the cooperative base salary (actual consumption/ maximum budget) has been generated.",
	'actualPlatformValueTip': 'The value of the media that represents the actual activity of the activity and the media value most likely to be achieved in the event of the activity, it is noted that the actual media value may exceed the predicted value (the media value that is most likely to be generated in the actual production of the media value/ prediction)',
	'information': {
	  'name': 'contacts',
	  'displayName': 'nickname',
	  'email': 'Contact mailbox',
	  'phone': 'contact numbe',
	  'currency': 'Transaction Currency',
	  'companyName': 'Company name',
	  'companyType': 'Type of company',
	  'companyCountry': 'Company Country',
	  'website': "Company's website",
	  'industry': 'Focus on the industry',
	  'pleasePhone': 'Please enter your phone numbe',
	  'pleaseEmail': 'Contact E-mail',
	  'pleaseName': 'Please enter a contact name',
	  'notNull': 'Cannot be empty',
	  'laterVer': 'post-revalidation',
	  'getVer': 'Get a verification code',
	  'pleaseVer': 'Please enter a verification code',
	  'choseM': 'Select Currency',
	  'tip': 'Tips: Please carefully confirm the platform transaction currency, and once the selected cannot be changed',
	  'sex': 'sex',
	  'country': 'country',
	  'pleaseChose': 'Please select',
	  'morThree': 'Up to three',
	  'save': 'save',
	  'brand': 'brand end',
	  'agency': 'the advertising party',
	  'cny': 'Renminbi (RMB) ',
	  'usd': 'American dolla',
	  'aud': 'Dollar A',
	  'wellcomText': 'Welcome to the Gate! To provide you with better service, please fill in the following information before use:',
	  'china': 'China',
	  'au': 'Australia',
	  'usa': 'America',
	  'otherPhone': 'Custom international zone numbe',
	  'pleasFillPhone': 'Please add the home international area number when filling in the mobile phone number. Otherwise, the verification code cannot be received.'
	},
	'campaign': {
	  'form': {
		'campaignName': 'Activity name',
		'industries': 'Promotion industry',
		'brandName': 'Brand name',
		'brandDescription': 'Brand introduction',
		'brandUrl': 'Brand Introduction Link',
		'targetAreas': 'target area ',
		'budget': 'Budget for activities',
		'startDate': 'activity start time',
		'continuous': 'Activity duration cycle',
		'duration': 'a week',
		'copy': 'Activity Text',
		'refLink': 'active jump link',
		'upLoadImg': 'Upload pictures'
	  },
	  'isRevert': 'Cancellation activity',
	  'revertInfo': 'You can have no responsibility to cancel the activity before the start time of the distance activity for more than 24 hours. The activity cannot be restored after the activity is revoked. Do you want to confirm the revocation of this activity?',
	  'activityPreview': 'Active Preview',
	  'tabs': {
		'banner': 'implantation',
		'custom': 'custom made'
	  },
	  'bannerStep': [
		'Select the type of activity',
		'Fill in the activity requirements',
		'Upload active content',
		'Confirm the activity policy',
		'Pre-stored activity expenses'
	  ],
	  'customStep': [
		'Select the type of activity',
		'Fill in the activity requirements',
		'Upload active content',
		'Confirm the activity policy',
		'Pre-stored activity expenses'
	  ]
	},
	'user': {
	  'fans': 'vermicelli made from bean starch, etc. ',
	  'fansNumber': 'Number of fans',
	  'post': 'invitation',
	  'postNumber': 'Number of posts'
	},
	'data': {
	  'generation': 'In data generation, please...',
	  'allPosts': 'All Posts',
	  'no': 'Not available '
	},
	'btn': {
	  'cancel': 'cancel',
	  'next': 'next step',
	  'previous': 'The last step.',
	  'saveAndNext': 'Save and Next',
	  'previewCampaign': 'Active Preview',
	  'contentPreview': 'Preview of implant content',
	  'customCampaignStrategy': 'Custom activity policy',
	  'save': 'save',
	  'refresh': 'Another wave.',
	  'confirm': 'affirm',
	  'restoreMatch': 'Discard customization and reset system policy',
	  'add': 'add',
	  'added': 'Added',
	  'pay': 'to pay',
	  'back': 'return',
	  'walletPayment': 'balance payment'
	}
  }
  